name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./filebeat
          file: ./filebeat/Dockerfile
          push: true
          tags: ttbb/filebeat:nake
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./heartbeat
          file: ./heartbeat/Dockerfile
          push: true
          tags: ttbb/heartbeat:nake
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./metricbeat
          file: ./metricbeat/Dockerfile
          push: true
          tags: ttbb/metricbeat:nake
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./packetbeat
          file: ./packetbeat/Dockerfile
          push: true
          tags: ttbb/packetbeat:nake